/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

//! Shared trait for Arrow RecordBatch buffer types.
//!
//! `RecordBatchBuffer` is the trait generated by
//! `#[derive(RecordBatchRow)]` (from `monarch_record_batch_macros`).
//! It is extracted here so the derive macro can be used from any
//! Monarch crate, not only `monarch_distributed_telemetry`.

use datafusion::arrow::error::ArrowError;
use datafusion::arrow::record_batch::RecordBatch;
// Re-export the derive macro so consumers only need to depend on this
// crate.
pub use monarch_record_batch_macros::RecordBatchRow;

/// Trait for buffer types that can produce Arrow RecordBatches.
///
/// Auto-implemented by `#[derive(RecordBatchRow)]` from
/// `monarch_record_batch_macros`.
pub trait RecordBatchBuffer {
    /// Number of rows currently buffered.
    fn len(&self) -> usize;

    /// Whether the buffer is empty.
    fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Drain buffered rows into a [`RecordBatch`].
    ///
    /// After this call the buffer is empty (fields are consumed via
    /// `std::mem::take`). The only failure mode is Arrow schema/batch
    /// construction, so the error type is [`ArrowError`] rather than
    /// a catch-all.
    fn drain_to_record_batch(&mut self) -> Result<RecordBatch, ArrowError>;
}
