# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# pyre-strict
from typing import Any, final

from monarch._rust_bindings.monarch_hyperactor.pytokio import Handle, PythonTask

@final
class _RdmaMemoryRegionView:
    def __init__(self, addr: int, size_in_bytes: int) -> None: ...

@final
class _LocalMemoryHandle:
    @property
    def addr(self) -> int: ...
    @property
    def size(self) -> int: ...
    def read_at(self, offset: int, size: int) -> bytes: ...
    def write_at(self, offset: int, data: bytes) -> None: ...
    def downgrade(self) -> _WeakLocalMemoryHandle | None: ...
    def __repr__(self) -> str: ...

@final
class _WeakLocalMemoryHandle:
    @property
    def addr(self) -> int: ...
    @property
    def size(self) -> int: ...
    def upgrade(self) -> _LocalMemoryHandle | None: ...
    def __repr__(self) -> str: ...

def _make_local_memory_handle_from_memoryview(mv: memoryview) -> _LocalMemoryHandle: ...
def _make_local_memory_handle_from_tensor(tensor: Any) -> _LocalMemoryHandle: ...
def _assert_1d_contiguous(buf: Any) -> None: ...
def _get_memoryview_addr_and_size(mv: memoryview) -> tuple[int, int]: ...
def _get_tensor_addr_and_size(tensor: Any) -> tuple[int, int]: ...
@final
class _RdmaManager:
    @classmethod
    def ensure_init_rdma_manager_nonblocking(
        cls,
        proc_mesh_shared: Any,
        caller: Any,
    ) -> Handle[None]: ...

class RdmaInitError(Exception):
    """Raised when the RDMA manager owner reports a typed initialization failure."""

    ...

@final
class _RdmaBuffer:
    name: str

    @classmethod
    def create_rdma_buffer_blocking(
        cls,
        local: _LocalMemoryHandle,
        client: Any,
        rdma_manager_init: Handle[None],
    ) -> _RdmaBuffer: ...
    def drop(
        self, client: Any, rdma_manager_init: Handle[None]
    ) -> PythonTask[None]: ...
    def size(self) -> int: ...
    def owner_actor_id(self) -> str: ...
    def __reduce__(self) -> tuple[Any, ...]: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def new_from_json(json: str) -> _RdmaBuffer: ...

@final
class _RdmaAction:
    """Builder for a batched RDMA action. Stage `read_into` / `write_from`
    ops then call `submit` to dispatch them. Local-memory races (writes
    overlapping anything, two writes from disjoint local sources are
    fine) are caught eagerly in the `add_*` calls.
    """

    def __init__(self) -> None: ...
    def add_read_into_local(
        self, remote: _RdmaBuffer, local: _LocalMemoryHandle
    ) -> None: ...
    def add_write_from_local(
        self, remote: _RdmaBuffer, local: _LocalMemoryHandle
    ) -> None: ...
    def submit(
        self, client: Any, timeout: int, rdma_manager_init: Handle[None]
    ) -> PythonTask[None]: ...

def is_ibverbs_available() -> bool: ...
def rdma_supported() -> bool: ...
