# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# pyre-strict

"""In-allocation runner for ``SlurmJob`` batch mode.

Invoked as the body of the sbatch script generated by
``apply(client_script=...)``. Runs on the head node and:

  1. seeds a worker on every node (one task per node),
  2. runs the client with ``MONARCH_BATCH_JOB=1`` so its cached ``BatchJob``
     reconnects to this allocation,
  3. terminates the workers in a ``finally``.

When this process exits the allocation is freed with the client's exit status.
"""

import argparse
import os
import shlex
import subprocess
import sys
from typing import List, Optional

from monarch._src.job._batch_env import MONARCH_BATCH_JOB_ENV

# Bootstraps one monarch worker bound to this node's hostname. Passed as python
# ``-c`` argv (no shell), so quoting inside is irrelevant.
_WORKER_BOOTSTRAP: str = (
    "import socket; from monarch.actor import run_worker_loop_forever; "
    'run_worker_loop_forever(address=f"tcp://{socket.gethostname()}:%d", '
    'ca="trust_all_connections")'
)


def main(argv: Optional[List[str]] = None) -> None:
    parser = argparse.ArgumentParser(prog="monarch._src.job._slurm_batch")
    parser.add_argument("--port", type=int, default=22222)
    parser.add_argument("client", help="client command to run inside the allocation")
    args = parser.parse_args(argv)

    # No warmup wait: the client's attach retries with backoff, so workers that
    # are still booting are handled by the channel layer, not a sleep here.
    workers = subprocess.Popen(
        [
            "srun",
            "--ntasks-per-node=1",
            sys.executable,
            "-c",
            _WORKER_BOOTSTRAP % args.port,
        ]
    )
    try:
        env = dict(os.environ, **{MONARCH_BATCH_JOB_ENV: "1"})
        returncode = subprocess.run(shlex.split(args.client), env=env).returncode
    finally:
        if workers.poll() is None:
            workers.terminate()
            try:
                workers.wait(timeout=30)
            except subprocess.TimeoutExpired:
                workers.kill()
    sys.exit(returncode)


if __name__ == "__main__":
    main()
