# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# pyre-unsafe

from monarch._rust_bindings.monarch_hyperactor.context import Instance

class ChainCtx: ...

class ChainServer:
    @property
    def addr(self) -> str: ...

class ChainSession: ...

def new_ctx(block_size: int) -> ChainCtx: ...
def serve(bind_addr: str | None = None) -> ChainServer: ...
def serve_port(instance: Instance) -> ChainServer: ...
def connect(addr: str, num_streams: int = ...) -> ChainSession: ...
def send_block(
    session: ChainSession, data: bytes, chunk_size: int, tag: int
) -> int: ...
def validate_port_addr(addr: str) -> None: ...
def send_block_to_port(
    instance: Instance, port: str, data: bytes, chunk_size: int, tag: int
) -> int: ...
def forward(
    server: ChainServer,
    successor: str | None,
    ctx: ChainCtx,
    num_streams: int = ...,
) -> None: ...
def ctx_wait_into(
    ctx: ChainCtx, dst_addr: int, dst_len: int, want: int, timeout_ms: int
) -> None: ...
def ctx_close(ctx: ChainCtx) -> None: ...
