/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

//! Remote references: typed wrappers around [`ActorRef`] or [`PortRef`] for type-safe message sending.

use std::fmt;
use std::marker::PhantomData;
use std::str::FromStr;

use serde::Deserialize;
use serde::Serialize;
use typeuri::Named;

use crate::actor::Referable;
use crate::id::ActorId;
use crate::id::Label;
use crate::mailbox::RemoteMessage;
use crate::ref_::ActorRef;
use crate::ref_::Location;
use crate::ref_::PortRef;
use crate::ref_::RefParseError;

/// Marker trait: `Remote<T>` can send message `M` when `T: Accepts<M>`.
///
/// - For actor/behavior types: generated by `#[export]`/`behavior!` (one impl per handled message).
/// - For message types: blanket `impl<M: RemoteMessage> Accepts<M> for M {}` covers identity.
pub trait Accepts<M: RemoteMessage>: Named {}

impl<M: RemoteMessage> Accepts<M> for M {}

/// The inner reference: either an actor or a port.
#[derive(Clone, Serialize, Deserialize, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub(crate) enum RemoteRef {
    Actor(ActorRef),
    Port(PortRef),
}

impl RemoteRef {
    /// Returns the actor id.
    pub(crate) fn actor_id(&self) -> &ActorId {
        match self {
            RemoteRef::Actor(r) => r.id(),
            RemoteRef::Port(r) => r.actor_id(),
        }
    }

    /// Returns the location.
    pub(crate) fn location(&self) -> &Location {
        match self {
            RemoteRef::Actor(r) => r.location(),
            RemoteRef::Port(r) => r.location(),
        }
    }
}

impl fmt::Display for RemoteRef {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RemoteRef::Actor(r) => fmt::Display::fmt(r, f),
            RemoteRef::Port(r) => fmt::Display::fmt(r, f),
        }
    }
}

/// A typed remote actor reference, wrapping an [`ActorRef`] or [`PortRef`]
/// with a type parameter for type-safe message sending.
#[derive(Clone, Serialize, Deserialize, typeuri::Named)]
pub struct Remote<A: Named> {
    inner: RemoteRef,
    #[serde(skip)]
    _phantom: PhantomData<fn() -> A>,
}

impl<A: Named> Remote<A> {
    /// Create a new [`Remote`] reference from an [`ActorRef`].
    pub fn new(actor_ref: ActorRef) -> Self {
        Self {
            inner: RemoteRef::Actor(actor_ref),
            _phantom: PhantomData,
        }
    }

    /// Create a new [`Remote`] reference from a [`PortRef`].
    pub fn from_port(port_ref: PortRef) -> Self {
        Self {
            inner: RemoteRef::Port(port_ref),
            _phantom: PhantomData,
        }
    }

    /// Returns the actor id.
    pub fn actor_id(&self) -> &ActorId {
        self.inner.actor_id()
    }

    /// Returns the location.
    pub fn location(&self) -> &Location {
        self.inner.location()
    }

    /// Send a message to this remote.
    ///
    /// For actor-typed remotes (`Remote<MyActor>`), `A: Accepts<M>` is
    /// generated by `#[export]` / `behavior!`.
    /// For message-typed remotes (`Remote<Ping>`), the blanket
    /// `impl<M: RemoteMessage> Accepts<M> for M` covers identity.
    pub fn send<M: RemoteMessage>(&self, _message: M) -> Result<(), anyhow::Error>
    where
        A: Accepts<M>,
    {
        // No-op: actual send implementation deferred to channel integration.
        Ok(())
    }
}

impl<A: Referable> Remote<A> {
    /// Narrow to a single-message remote for message type `M`.
    pub fn narrow<M: RemoteMessage>(self) -> Remote<M>
    where
        A: Accepts<M>,
    {
        Remote {
            inner: self.inner,
            _phantom: PhantomData,
        }
    }
}

impl<A: Named> PartialEq for Remote<A> {
    fn eq(&self, other: &Self) -> bool {
        self.inner == other.inner
    }
}

impl<A: Named> Eq for Remote<A> {}

impl<A: Named> std::hash::Hash for Remote<A> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.inner.hash(state);
    }
}

impl<A: Named> PartialOrd for Remote<A> {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl<A: Named> Ord for Remote<A> {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.inner.cmp(&other.inner)
    }
}

impl<A: Named> fmt::Display for Remote<A> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Display::fmt(&self.inner, f)
    }
}

fn fmt_remote_debug(
    f: &mut fmt::Formatter<'_>,
    short_type: &str,
    actor_label: Option<&Label>,
    proc_label: Option<&Label>,
    id_display: &dyn fmt::Display,
    location: &Location,
) -> fmt::Result {
    match (actor_label, proc_label) {
        (Some(actor_label), Some(proc_label)) => {
            write!(
                f,
                "<'{}<{}>.{}' {}@{}>",
                actor_label, short_type, proc_label, id_display, location
            )
        }
        (Some(actor_label), None) => {
            write!(
                f,
                "<'{}<{}>' {}@{}>",
                actor_label, short_type, id_display, location
            )
        }
        (None, Some(proc_label)) => {
            write!(
                f,
                "<'<{}>.{}' {}@{}>",
                short_type, proc_label, id_display, location
            )
        }
        (None, None) => {
            write!(f, "<'<{}>' {}@{}>", short_type, id_display, location)
        }
    }
}

impl<A: Named> fmt::Debug for Remote<A> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let typename = A::typename();
        let short = typename.rsplit("::").next().unwrap_or(typename);
        let actor_id = self.inner.actor_id();
        match &self.inner {
            RemoteRef::Actor(r) => fmt_remote_debug(
                f,
                short,
                actor_id.label(),
                actor_id.proc_id().label(),
                r.id(),
                r.location(),
            ),
            RemoteRef::Port(r) => fmt_remote_debug(
                f,
                short,
                actor_id.label(),
                actor_id.proc_id().label(),
                r.id(),
                r.location(),
            ),
        }
    }
}

impl<A: Named> FromStr for Remote<A> {
    type Err = RefParseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let at = s.find('@').ok_or(RefParseError::MissingSeparator)?;
        let id_part = &s[..at];
        if id_part.contains(':') {
            let port_ref: PortRef = s.parse()?;
            Ok(Self::from_port(port_ref))
        } else {
            let actor_ref: ActorRef = s.parse()?;
            Ok(Self::new(actor_ref))
        }
    }
}

#[cfg(test)]
mod tests {
    use std::hash::Hash;

    use serde::Deserialize;
    use serde::Serialize;

    use super::*;
    use crate::actor::Referable;
    use crate::channel::ChannelAddr;
    use crate::id::Label;
    use crate::id::PortId;
    use crate::id::ProcId;
    use crate::id::Uid;
    use crate::port::Port;

    #[derive(Clone, Serialize, Deserialize, typeuri::Named)]
    struct MyWorker;

    // A test message type.
    #[derive(Debug, Clone, Serialize, Deserialize, typeuri::Named)]
    struct Ping;

    #[derive(Debug, Clone, Serialize, Deserialize, typeuri::Named)]
    struct Pong;

    // A test actor type (manually impl the traits that #[export] would generate).
    #[derive(Debug, Clone, Serialize, Deserialize, typeuri::Named)]
    struct TestActor;
    impl Referable for TestActor {}
    impl Accepts<Ping> for TestActor {}
    impl Accepts<Pong> for TestActor {}

    fn make_actor_ref(actor_label: Option<&str>, proc_label: Option<&str>) -> ActorRef {
        let aid = ActorId::new(
            Uid::Instance(0xabc123),
            ProcId::new(
                Uid::Instance(0xdef456),
                proc_label.map(|l| Label::new(l).unwrap()),
            ),
            actor_label.map(|l| Label::new(l).unwrap()),
        );
        let loc: Location = ChannelAddr::Local(42).into();
        ActorRef::new(aid, loc)
    }

    fn make_port_ref(actor_label: Option<&str>, proc_label: Option<&str>) -> PortRef {
        let aid = ActorId::new(
            Uid::Instance(0xabc123),
            ProcId::new(
                Uid::Instance(0xdef456),
                proc_label.map(|l| Label::new(l).unwrap()),
            ),
            actor_label.map(|l| Label::new(l).unwrap()),
        );
        let port_id = PortId::new(aid, Port::from(42));
        let loc: Location = ChannelAddr::Local(7).into();
        PortRef::new(port_id, loc)
    }

    fn make_remote<A: Named>() -> Remote<A> {
        Remote::new(make_actor_ref(Some("my-actor"), Some("my-proc")))
    }

    fn make_port_remote<A: Named>() -> Remote<A> {
        Remote::from_port(make_port_ref(Some("my-actor"), Some("my-proc")))
    }

    // --- Actor variant tests ---

    #[test]
    fn test_remote_construction_and_accessors() {
        let aref = make_actor_ref(Some("my-actor"), Some("my-proc"));
        let remote = Remote::<MyWorker>::new(aref.clone());
        assert_eq!(remote.actor_id(), aref.id());
        assert_eq!(remote.location(), aref.location());
    }

    #[test]
    fn test_remote_display_matches_actor_ref() {
        let aref = make_actor_ref(Some("my-actor"), Some("my-proc"));
        let remote = Remote::<MyWorker>::new(aref.clone());
        assert_eq!(remote.to_string(), aref.to_string());
    }

    #[test]
    fn test_remote_debug_all_labels() {
        let remote = Remote::<MyWorker>::new(make_actor_ref(Some("my-actor"), Some("my-proc")));
        assert_eq!(
            format!("{:?}", remote),
            "<'my-actor<MyWorker>.my-proc' 0000000000abc123.0000000000def456@inproc://42>"
        );
    }

    #[test]
    fn test_remote_debug_actor_label_only() {
        let remote = Remote::<MyWorker>::new(make_actor_ref(Some("my-actor"), None));
        assert_eq!(
            format!("{:?}", remote),
            "<'my-actor<MyWorker>' 0000000000abc123.0000000000def456@inproc://42>"
        );
    }

    #[test]
    fn test_remote_debug_no_labels() {
        let remote = Remote::<MyWorker>::new(make_actor_ref(None, None));
        assert_eq!(
            format!("{:?}", remote),
            "<'<MyWorker>' 0000000000abc123.0000000000def456@inproc://42>"
        );
    }

    #[test]
    fn test_remote_debug_proc_label_only() {
        let remote = Remote::<MyWorker>::new(make_actor_ref(None, Some("my-proc")));
        assert_eq!(
            format!("{:?}", remote),
            "<'<MyWorker>.my-proc' 0000000000abc123.0000000000def456@inproc://42>"
        );
    }

    #[test]
    fn test_remote_fromstr_roundtrip() {
        let aref = make_actor_ref(Some("my-actor"), Some("my-proc"));
        let remote = Remote::<MyWorker>::new(aref);
        let s = remote.to_string();
        let parsed: Remote<MyWorker> = s.parse().unwrap();
        assert_eq!(remote, parsed);
    }

    #[test]
    fn test_remote_serde_roundtrip() {
        let remote = Remote::<MyWorker>::new(make_actor_ref(Some("my-actor"), Some("my-proc")));
        let json = serde_json::to_string(&remote).unwrap();
        let parsed: Remote<MyWorker> = serde_json::from_str(&json).unwrap();
        assert_eq!(remote, parsed);
    }

    #[test]
    fn test_remote_eq_and_hash() {
        use std::collections::hash_map::DefaultHasher;
        use std::hash::Hasher;

        let aref = make_actor_ref(Some("actor"), Some("proc"));
        let a = Remote::<MyWorker>::new(aref.clone());
        let b = Remote::<MyWorker>::new(aref);
        assert_eq!(a, b);

        let hash = |r: &Remote<MyWorker>| {
            let mut h = DefaultHasher::new();
            r.hash(&mut h);
            h.finish()
        };
        assert_eq!(hash(&a), hash(&b));
    }

    #[test]
    fn test_remote_ord() {
        let a = Remote::<MyWorker>::new(make_actor_ref(Some("a"), None));
        let b = Remote::<MyWorker>::new(make_actor_ref(Some("b"), None));
        // Same ids, so ordering should be equal.
        assert_eq!(a.cmp(&b), std::cmp::Ordering::Equal);
    }

    #[test]
    fn test_send_actor_typed_remote() {
        let remote: Remote<TestActor> = make_remote();
        remote.send(Ping).unwrap();
        remote.send(Pong).unwrap();
    }

    #[test]
    fn test_send_message_typed_remote() {
        let remote: Remote<Ping> = make_remote();
        remote.send(Ping).unwrap();
    }

    #[test]
    fn test_narrow() {
        let actor_remote: Remote<TestActor> = make_remote();
        let narrowed: Remote<Ping> = actor_remote.narrow();
        narrowed.send(Ping).unwrap();
    }

    // --- Port variant tests ---

    #[test]
    fn test_port_remote_construction_and_accessors() {
        let pref = make_port_ref(Some("my-actor"), Some("my-proc"));
        let remote = Remote::<MyWorker>::from_port(pref.clone());
        assert_eq!(remote.actor_id(), pref.actor_id());
        assert_eq!(remote.location(), pref.location());
    }

    #[test]
    fn test_port_remote_display_matches_port_ref() {
        let pref = make_port_ref(Some("my-actor"), Some("my-proc"));
        let remote = Remote::<MyWorker>::from_port(pref.clone());
        assert_eq!(remote.to_string(), pref.to_string());
    }

    #[test]
    fn test_port_remote_debug_all_labels() {
        let remote =
            Remote::<MyWorker>::from_port(make_port_ref(Some("my-actor"), Some("my-proc")));
        assert_eq!(
            format!("{:?}", remote),
            "<'my-actor<MyWorker>.my-proc' 0000000000abc123.0000000000def456:42@inproc://7>"
        );
    }

    #[test]
    fn test_port_remote_debug_no_labels() {
        let remote = Remote::<MyWorker>::from_port(make_port_ref(None, None));
        assert_eq!(
            format!("{:?}", remote),
            "<'<MyWorker>' 0000000000abc123.0000000000def456:42@inproc://7>"
        );
    }

    #[test]
    fn test_port_remote_fromstr_roundtrip() {
        let pref = make_port_ref(Some("my-actor"), Some("my-proc"));
        let remote = Remote::<MyWorker>::from_port(pref);
        let s = remote.to_string();
        let parsed: Remote<MyWorker> = s.parse().unwrap();
        assert_eq!(remote, parsed);
    }

    #[test]
    fn test_port_remote_serde_roundtrip() {
        let remote =
            Remote::<MyWorker>::from_port(make_port_ref(Some("my-actor"), Some("my-proc")));
        let json = serde_json::to_string(&remote).unwrap();
        let parsed: Remote<MyWorker> = serde_json::from_str(&json).unwrap();
        assert_eq!(remote, parsed);
    }

    #[test]
    fn test_port_remote_eq_and_hash() {
        use std::collections::hash_map::DefaultHasher;
        use std::hash::Hasher;

        let pref = make_port_ref(Some("actor"), Some("proc"));
        let a = Remote::<MyWorker>::from_port(pref.clone());
        let b = Remote::<MyWorker>::from_port(pref);
        assert_eq!(a, b);

        let hash = |r: &Remote<MyWorker>| {
            let mut h = DefaultHasher::new();
            r.hash(&mut h);
            h.finish()
        };
        assert_eq!(hash(&a), hash(&b));
    }

    #[test]
    fn test_actor_and_port_remote_not_equal() {
        let actor_remote: Remote<MyWorker> = make_remote();
        let port_remote: Remote<MyWorker> = make_port_remote();
        assert_ne!(actor_remote, port_remote);
    }

    #[test]
    fn test_narrow_port_variant() {
        let actor_remote: Remote<TestActor> = make_port_remote();
        let narrowed: Remote<Ping> = actor_remote.narrow();
        narrowed.send(Ping).unwrap();
    }

    #[test]
    fn test_send_port_typed_remote() {
        let remote: Remote<TestActor> = make_port_remote();
        remote.send(Ping).unwrap();
        remote.send(Pong).unwrap();
    }
}
